services:
  - type: web
    name: notagentsbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Укажешь в Render вручную через Settings → Environment
